import bcrypt from 'bcryptjs';

// The data for products and users that will be used to fill the mongodb database
const data = {
  users: [
    {
      name: 'James',
      email: 'admin@unlockedphonestore.ca',
      password: bcrypt.hashSync('password'),
      admin: true,
    },
    {
      name: 'temp',
      email: 'user1@unlockedphonestore.ca',
      password: bcrypt.hashSync('password'),
      admin: false,
    },
  ],
  products: [
    {
      name: 'Samsung Galaxy S22',
      slug: 'samsung-galaxy-s22',
      category: 'Samsung',
      image: '/images/p1.jpg',
      price: '909',
      countInStock: '25',
      brand: 'Samsung',
      rating: '4.5',
      numReviews: '23',
      description:
        'The newest and most powerful Samsung Android phone available on the market.',
      batterySize: '128GB',
      colour: 'Black',
    },
    {
      name: 'Apple iPhone 13',
      slug: 'apple-iphone-13',
      category: 'Apple',
      image: '/images/p2.jpg',
      price: '1399',
      countInStock: '0',
      brand: 'Apple',
      rating: '4',
      numReviews: '10',
      description:
        'The newest and most powerful Apple IOS phone available on the market.',
      batterySize: '128GB',
      colour: 'Pink',
    },
    {
      name: 'Google Pixel 6',
      slug: 'google-pixel-6',
      category: 'Google',
      image: '/images/p3.jpg',
      price: '699',
      countInStock: '23',
      brand: 'Google',
      rating: '3.5',
      numReviews: '6',
      description:
        'The Google Pixel 6 5G phone has a powerful camera system, next-gen Titan M2 security, and the custom-built Google Tensor processor.',
      batterySize: '64GB',
      colour: 'Seafoam Green',
    },
    {
      name: 'Samsung Galaxy S20',
      slug: 'samsung-galaxy-s20',
      category: 'Samsung',
      image: '/images/p4.jpg',
      price: '418',
      countInStock: '10',
      brand: 'Samsung',
      rating: '3',
      numReviews: '12',
      description:
        'Experience smartphone bliss with the Samsung Galaxy S20. It has a 6.2" Dynamic AMOLED infinity-o display for stunning imagery.',
      batterySize: '128GB',
      colour: 'Black',
    },
    {
      name: 'Samsung Galaxy A03',
      slug: 'samsung-galaxy-a03',
      category: 'Samsung',
      image: '/images/p5.jpg',
      price: '169',
      countInStock: '4',
      brand: 'Samsung',
      rating: '3.5',
      numReviews: '116',
      description:
        'If you value simplicity, Galaxy A03s is the phone for you. That means you get the awesome essentials like a long-lasting battery, high-definition display and multi-lens camera, all in one of ourmost affordable phones.',
      batterySize: '32GB',
      colour: 'Black',
    },
    {
      name: 'Apple iPhone XR',
      slug: 'apple-iphone-xr',
      category: 'Apple',
      image: '/images/p6.jpg',
      price: '379',
      countInStock: '30',
      brand: 'Apple',
      rating: '4.5',
      numReviews: '10548',
      description:
        '6.1" LCD Multi-Touch display with IPS technology, 828 x 1792 pixels, 19.5:9 ratio, upgradable to iOS 14.7, Bluetooth 5.0',
      batterySize: '64GB',
      colour: 'Black',
    },
    {
      name: 'Apple iPhone 11',
      slug: 'apple-iphone-11',
      category: 'Apple',
      image: '/images/p7.jpg',
      price: '568',
      countInStock: '30',
      brand: 'Apple',
      rating: '4.5',
      numReviews: '2797',
      description:
        'It features a 1792 x 828 resolution at 326ppi, a 1400:1 contrast ratio, 625 nits max brightness, True Tone support for adjusting the white balance to the ambient lighting, and wide color support.',
      batterySize: '64GB',
      colour: 'Purple',
    },
    {
      name: 'Apple iPhone 12',
      slug: 'apple-iphone-12',
      category: 'Apple',
      image: '/images/p8.jpg',
      price: '795',
      countInStock: '25',
      brand: 'Apple',
      rating: '4.5',
      numReviews: '492',
      description:
        'The iPhone 12 features a 6.1-inch (15 cm) display with Super Retina XDR OLED technology at a resolution of 2532 × 1170 pixels and a pixel density of about 460 ppi.',
      batterySize: '64GB',
      colour: 'Blue',
    },
    {
      name: 'Google Pixel 4 XL',
      slug: 'google-pixel-4-xl',
      category: 'Google',
      image: '/images/p9.jpg',
      price: '479',
      countInStock: '20',
      brand: 'Google',
      rating: '4.5',
      numReviews: '415',
      description:
        'Pixel 4 is the phone Made the Google way. So it’s built around the helpful Google software you know and love, that’s always getting better.',
      batterySize: '128GB',
      colour: 'Black',
    },
    {
      name: 'Google Pixel 5a',
      slug: 'google-pixel-5a',
      category: 'Google',
      image: '/images/p10.jpg',
      price: '619',
      countInStock: '54',
      brand: 'Google',
      rating: '3.5',
      numReviews: '30',
      description:
        'The Google Pixel 5a delivers the same experience as the Pixel 5 or Pixel 4a 5G, but for only $619. It’s also got the biggest battery ever in a Pixel — at least until the Pixel 6 Pro came along — and it’s the first A-series Pixel to sport water resistance.',
      batterySize: '128GB',
      colour: 'Black',
    },
  ],
};

export default data;
